package main

import "time"

var timestamp = time.Now().Format("20060102150405")

var providers = provider{
	"aws": {
		name:         "Amazon Web Services",
		hostTemplate: "s3.%s.amazonaws.com",
		regions: []*region{
			{name: "af-south-1", location: "Cape Town, ZA"},
			{name: "ap-east-1", location: "Hong Kong, CN"},
			{name: "ap-northeast-1", location: "Tokyo, JP"},
			{name: "ap-northeast-2", location: "Seoul, KR"},
			{name: "ap-northeast-3", location: "Osaka, JP"},
			{name: "ap-south-1", location: "Mumbai, IN"},
			{name: "ap-southeast-1", location: "Singapore, SG"},
			{name: "ap-southeast-2", location: "Sydney, AU"},
			{name: "ap-southeast-3", location: "Jakarta, ID"},
			{name: "ca-central-1", location: "Montreal, CA"},
			{name: "eu-central-1", location: "Frankfurt, DE"},
			{name: "eu-north-1", location: "Stockholm, SE"},
			{name: "eu-south-1", location: "Milan, IT"},
			{name: "eu-west-1", location: "Dublin, IE"},
			{name: "eu-west-2", location: "London, UK"},
			{name: "eu-west-3", location: "Paris, FR"},
			{name: "me-south-1", location: "Bahrain, BH"},
			{name: "sa-east-1", location: "Sao Paulo, BR"},
			{name: "us-east-1", location: "North Virginia, US"},
			{name: "us-east-2", location: "Ohio, US"},
			{name: "us-west-1", location: "North California, US"},
			{name: "us-west-2", location: "Oregon, US"},
		},
	},
	"alibaba": {
		name:         "Alibaba Cloud",
		hostTemplate: "oss-%s.aliyuncs.com",
		regions: []*region{
			{name: "ap-southeast-1", location: "Singapore, SG"},
			{name: "ap-southeast-2", location: "Sydney, AU"},
			{name: "ap-southeast-3", location: "Kuala Lumpur, MY"},
			{name: "ap-southeast-5", location: "Jakarta, ID"},
			{name: "ap-southeast-6", location: "Manila, PH"},
			{name: "ap-southeast-7", location: "Bangkok, TH"},
			{name: "ap-northeast-1", location: "Tokyo, JP"},
			{name: "ap-northeast-2", location: "Seoul, KR"},
			{name: "ap-south-1", location: "Mumbai, IN"},
			{name: "cn-beijing", location: "Beijing, CN"},
			{name: "cn-chengdu", location: "Chengdu, CN"},
			{name: "cn-guangzhou", location: "Guangzhou, CN"},
			{name: "cn-hangzhou", location: "Hangzhou, CN"},
			{name: "cn-heyuan", location: "Heyuan, CN"},
			{name: "cn-hongkong", location: "Hong Kong, CN"},
			{name: "cn-huhehaote", location: "Huhehaote, CN"},
			{name: "cn-qingdao", location: "Qingdao, CN"},
			{name: "cn-shanghai", location: "Shanghai, CN"},
			{name: "cn-shenzhen", location: "Shenzhen, CN"},
			{name: "cn-wulanchabu", location: "Ulanqab, CN"},
			{name: "cn-zhangjiakou", location: "Zhangjiakou, CN"},
			{name: "eu-central-1", location: "Frankfurt, DE"},
			{name: "eu-west-1", location: "London, UK"},
			{name: "me-east-1", location: "Dubai, AE"},
			{name: "us-east-1", location: "Virginia, US"},
			{name: "us-west-1", location: "California, US"},
		},
	},
	"azure": {
		name:         "Microsoft Azure",
		hostTemplate: "https://av%s.blob.core.windows.net/probe/ping.js?" + timestamp,
		regions: []*region{
			{name: "eastasia", location: "Hong Kong, CN"},
			{name: "southeastasia", location: "Singapore, SG"},
			{name: "australiaeast", location: "New South Wales, AU"},
			{name: "australiasoutheast", location: "Victoria, AU"},
			{name: "australiacentral", location: "Canberra, AU"},
			{name: "australiacentral2", location: "Canberra, AU"},
			{name: "centralindia", location: "Pune, IN"},
			{name: "westindia", location: "Mumbai, IN", code: "indiawest9835"},
			{name: "southindia", location: "Chennai, IN"},
			{name: "japaneast", location: "Tokyo, JP"},
			{name: "japanwest", location: "Osaka, JP"},
			{name: "koreacentral", location: "Seoul, KR"},
			{name: "koreasouth", location: "Busan, KR"},
			{name: "northeurope", location: "Dublin, IE"},
			{name: "westeurope", location: "Amsterdam, NL"},
			{name: "francecentral", location: "Paris, FR"},
			{name: "francesouth", location: "Marseille, FR"},
			{name: "ukwest", location: "Cardiff, UK"},
			{name: "uksouth", location: "London, UK"},
			{name: "germanywestcentral", location: "Frankfurt, DE"},
			{name: "germanynorth", location: "Berlin, DE"},
			{name: "eastus", location: "Virginia, US"},
			{name: "eastus2", location: "Virginia, US"},
			{name: "centralus", location: "Iowa, US"},
			{name: "northcentralus", location: "Illinois, US"},
			{name: "southcentralus", location: "Texas, US"},
			{name: "westcentralus", location: "Wyoming, US"},
			{name: "westus", location: "California, US"},
			{name: "westus2", location: "Washington, US"},
			{name: "canadaeast", location: "Quebec City, CA"},
			{name: "canadacentral", location: "Toronto, CA"},
			{name: "brazilsouth", location: "Sao Paulo, BR"},
			{name: "brazilsoutheast", location: "Rio de Janeiro, BR"},
			{name: "southafricanorth", location: "Johannesburg, ZA"},
			{name: "southafricawest", location: "Cape Town, ZA"},
			{name: "norwayeast", location: "Oslo, Norway"},
			{name: "switzerlandwest", location: "Geneva, CH"},
			{name: "switzerlandnorth", location: "Zurich, CH"},
			{name: "uaecentral", location: "Abu Dhabi, AE"},
			{name: "uaenorth", location: "Dubai, AE"},
		},
	},
	"digitalocean": {
		name:         "Digital Ocean",
		hostTemplate: "speedtest-%s.digitalocean.com",
		regions: []*region{
			{name: "ams2", location: "Amsterdam, NL"},
			{name: "ams3", location: "Amsterdam, NL"},
			{name: "blr1", location: "Bangalore, IN"},
			{name: "fra1", location: "Frankfurt, DE"},
			{name: "lon1", location: "London, UK"},
			{name: "nyc1", location: "New York, US"},
			{name: "nyc2", location: "New York, US"},
			{name: "nyc3", location: "New York, US"},
			{name: "sfo1", location: "San Francisco, US"},
			{name: "sfo2", location: "San Francisco, US"},
			{name: "sfo3", location: "San Francisco, US"},
			{name: "sgp1", location: "Singapore, SG"},
			{name: "tor1", location: "Toronto, CA"},
		},
	},
	"gcp": {
		name: "Google Cloud Platform",
		regions: []*region{
			{name: "asia-east1", location: "Changhua County, TW", host: "https://asia-east1-5tkroniexa-de.a.run.app/api/ping"},
			{name: "asia-east2", location: "Hong Kong, CN", host: "https://asia-east2-5tkroniexa-df.a.run.app/api/ping"},
			{name: "asia-northeast1", location: "Tokyo, JP", host: "https://asia-northeast1-5tkroniexa-an.a.run.app/api/ping"},
			{name: "asia-northeast2", location: "Osaka, JP", host: "https://asia-northeast2-5tkroniexa-dt.a.run.app/api/ping"},
			{name: "asia-northeast3", location: "Seoul, KR", host: "https://asia-northeast3-5tkroniexa-du.a.run.app/api/ping"},
			{name: "asia-south1", location: "Mumbai, IN", host: "https://asia-south1-5tkroniexa-el.a.run.app/api/ping"},
			{name: "asia-south2", location: "Delhi, IN", host: "https://asia-south2-5tkroniexa-em.a.run.app/api/ping"},
			{name: "asia-southeast1", location: "Singapore, SG", host: "https://asia-southeast1-5tkroniexa-as.a.run.app/api/ping"},
			{name: "asia-southeast2", location: "Jakarta, ID", host: "https://asia-southeast2-5tkroniexa-et.a.run.app/api/ping"},
			{name: "australia-southeast1", location: "Sydney, AU", host: "https://australia-southeast1-5tkroniexa-ts.a.run.app/api/ping"},
			{name: "australia-southeast2", location: "Melbourne, AU", host: "https://australia-southeast2-5tkroniexa-km.a.run.app/api/ping"},
			{name: "europe-central2", location: "Warsaw, PL", host: "https://europe-central2-5tkroniexa-lm.a.run.app/api/ping"},
			{name: "europe-north1", location: "Hamina, FI", host: "https://europe-north1-5tkroniexa-lz.a.run.app/api/ping"},
			{name: "europe-southwest1", location: "Madrid, ES", host: "https://europe-southwest1-5tkroniexa-no.a.run.app/api/ping"},
			{name: "europe-west1", location: "St. Ghislain, BE", host: "https://europe-west1-5tkroniexa-ew.a.run.app/api/ping"},
			{name: "europe-west2", location: "London, UK", host: "https://europe-west2-5tkroniexa-nw.a.run.app/api/ping"},
			{name: "europe-west3", location: "Frankfurt, DE", host: "https://europe-west3-5tkroniexa-ey.a.run.app/api/ping"},
			{name: "europe-west4", location: "Eemshaven, NL", host: "https://europe-west4-5tkroniexa-ez.a.run.app/api/ping"},
			{name: "europe-west6", location: "Zurich, CH", host: "https://europe-west6-5tkroniexa-oa.a.run.app/api/ping"},
			{name: "europe-west8", location: "Milan, IT", host: "https://europe-west8-5tkroniexa-oc.a.run.app/api/ping"},
			{name: "europe-west9", location: "Paris, FR", host: "https://europe-west9-5tkroniexa-od.a.run.app/api/ping"},
			{name: "northamerica-northeast1", location: "Montreal, CA", host: "https://northamerica-northeast1-5tkroniexa-nn.a.run.app/api/ping"},
			{name: "northamerica-northeast2", location: "Toronto, CA", host: "https://northamerica-northeast2-5tkroniexa-pd.a.run.app/api/ping"},
			{name: "southamerica-east1", location: "Osasco, BR", host: "https://southamerica-east1-5tkroniexa-rj.a.run.app/api/ping"},
			{name: "southamerica-west1", location: "Santiago, CL", host: "https://southamerica-west1-5tkroniexa-tl.a.run.app/api/ping"},
			{name: "us-central1", location: "Council Bluffs, US", host: "https://us-central1-5tkroniexa-uc.a.run.app/api/ping"},
			{name: "us-east1", location: "Moncks Corner, US", host: "https://us-east1-5tkroniexa-ue.a.run.app/api/ping"},
			{name: "us-east4", location: "Ashburn, US", host: "https://us-east4-5tkroniexa-uk.a.run.app/api/ping"},
			{name: "us-east5", location: "Columbus, US", host: "https://us-east5-5tkroniexa-ul.a.run.app/api/ping"},
			{name: "us-south1", location: "Dallas, US", host: "https://us-south1-5tkroniexa-vp.a.run.app/api/ping"},
			{name: "us-west1", location: "The Dalles, US", host: "https://us-west1-5tkroniexa-uw.a.run.app/api/ping"},
			{name: "us-west2", location: "Los Angeles, US", host: "https://us-west2-5tkroniexa-wl.a.run.app/api/ping"},
			{name: "us-west3", location: "Salt Lake City, US", host: "https://us-west3-5tkroniexa-wm.a.run.app/api/ping"},
			{name: "us-west4", location: "Las Vegas, US", host: "https://us-west4-5tkroniexa-wn.a.run.app/api/ping"},
		},
	},
	"hetzner": {
		name:         "Hetzner Cloud",
		hostTemplate: "%s.icmp.hetzner.com",
		regions: []*region{
			{name: "ash", location: "Ashburn, US"},
			{name: "fsn", location: "Frankfurt, DE"},
			{name: "hel", location: "Helsinki, FI"},
			{name: "nbg", location: "Nurnberg, DE"},
		},
	},
	"ibm": {
		name:         "IBM Cloud",
		hostTemplate: "s3.%s.cloud-object-storage.appdomain.cloud",
		regions: []*region{
			{name: "ams03", location: "Amsterdam, NL"},
			{name: "au-syd", location: "Sydney, AU"},
			{name: "che01", location: "Chennai, IN"},
			{name: "eu-de", location: "Frankfurt, DE"},
			{name: "eu-gb", location: "London, UK"},
			{name: "hkg02", location: "Hong Kong, CN"},
			{name: "jp-osa", location: "Osaka, JP"},
			{name: "jp-tok", location: "Tokyo, JP"},
			{name: "mex01", location: "Mexico City, MX"},
			{name: "mil01", location: "Milan, IT"},
			{name: "mon01", location: "Montreal, CA"},
			{name: "par01", location: "Paris, FR"},
			{name: "sao01", location: "Sao Paulo, BR"},
			{name: "seo01", location: "Seoul, KR"},
			{name: "sjc04", location: "San Jose, US"},
			{name: "sng01", location: "Singapore, SG"},
			{name: "tor01", location: "Toronto, CA"},
			{name: "us-east", location: "Washington, US"},
			{name: "us-south", location: "Dallas, US"},
		},
	},
	"linode": {
		name:         "Linode",
		hostTemplate: "speedtest.%s.linode.com",
		regions: []*region{
			{name: "atlanta", location: "Atlanta, US"},
			{name: "dallas", location: "Dallas, US"},
			{name: "fremont", location: "Fremont, US"},
			{name: "frankfurt", location: "Frankfurt, DE"},
			{name: "london", location: "London, UK"},
			{name: "mumbai", location: "Mumbai, IN", code: "mumbai1"},
			{name: "newark", location: "Newark, US"},
			{name: "singapore", location: "Singapore, SG"},
			{name: "sydney", location: "Sydney, AU", code: "syd1"},
			{name: "tokyo", location: "Tokyo, JP", code: "tokyo2"},
			{name: "toronto", location: "Toronto, CA", code: "toronto1"},
		},
	},
	"oracle": {
		name:         "Oracle Cloud",
		hostTemplate: "objectstorage.%s.oraclecloud.com",
		regions: []*region{
			{name: "ap-chuncheon-1", location: "Chuncheon, KR"},
			{name: "ap-hyderabad-1", location: "Hyderabad, IN"},
			{name: "ap-melbourne-1", location: "Melbourne, AU"},
			{name: "ap-mumbai-1", location: "Mumbai, IN"},
			{name: "ap-osaka-1", location: "Osaka, JP"},
			{name: "ap-seoul-1", location: "Seoul, KR"},
			{name: "ap-sydney-1", location: "Sydney, AU"},
			{name: "ap-tokyo-1", location: "Tokyo, JP"},
			{name: "ca-montreal-1", location: "Montreal, CA"},
			{name: "ca-toronto-1", location: "Toronto, CA"},
			{name: "eu-amsterdam-1", location: "Amsterdam, NL"},
			{name: "eu-frankfurt-1", location: "Frankfurt, DE"},
			{name: "eu-zurich-1", location: "Zurich, CH"},
			{name: "me-dubai-1", location: "Dubai, AE"},
			{name: "me-jeddah-1", location: "Jeddah, SA"},
			{name: "sa-santiago-1", location: "Santiago, CL"},
			{name: "sa-saopaulo-1", location: "Sao Paulo, BR"},
			{name: "uk-cardiff-1", location: "Newport, UK"},
			{name: "uk-london-1", location: "London, UK"},
			{name: "us-ashburn-1", location: "Ashburn, US"},
			{name: "us-phoenix-1", location: "Phoenix, US"},
			{name: "us-sanjose-1", location: "San Jose, US"},
		},
	},
	"ovh": {
		name:         "OVH Cloud",
		hostTemplate: "s3.%s.cloud.ovh.net",
		regions: []*region{
			{name: "bhs", location: "Beauharnois, CA"},
			{name: "de", location: "Franckfurt, DE"},
			{name: "gra", location: "Gravelines, FR"},
			{name: "hil", location: "Hilsboro, US", host: "hil.proof.ovh.us"},
			{name: "sbg", location: "Strasbourg, FR"},
			{name: "sgp", location: "Singapore, SG"},
			{name: "syd", location: "Sidney, AU"},
			{name: "uk", location: "Erith, UK"},
			{name: "vin", location: "Vint Hill, US", host: "vin.proof.ovh.us"},
			{name: "waw", location: "Warsaw, PL"},
		},
	},
	"scaleway": {
		name:         "Scaleway",
		hostTemplate: "s3.%s.scw.cloud",
		regions: []*region{
			{name: "fr-par", location: "Paris, FR"},
			{name: "nl-ams", location: "Amsterdam, NL"},
			{name: "pl-waw", location: "Warsaw, PL"},
		},
	},
	"servers": {
		name:         "Servers.com",
		hostTemplate: "test.%s.servers.com",
		regions: []*region{
			{name: "ams1", location: "Amsterdam, NL"},
			{name: "ams2", location: "Haarlem, NL"},
			{name: "ams3", location: "Amsterdam, NL"},
			{name: "ams4", location: "Haarlem, NL"},
			{name: "dfw1", location: "Dallas, US"},
			{name: "dfw2", location: "Dallas, US"},
			{name: "dfw3", location: "Dallas, US"},
			{name: "hkg1", location: "Hong Kong, CN"},
			{name: "lon1", location: "Slough, UK"},
			{name: "lux1", location: "Roost, LU"},
			{name: "lux2", location: "Roost, LU"},
			{name: "sin1", location: "Singapore, SG"},
			{name: "sjc1", location: "San Jose, US"},
			{name: "was1", location: "Washington, US"},
			{name: "was2", location: "Washington, US"},
		},
	},
	"vultr": {
		name:         "Vultr",
		hostTemplate: "%s-ping.vultr.com",
		regions: []*region{
			{name: "ams-nl", location: "Amsterdam, NL"},
			{name: "bom-in", location: "Mumbai, IN"},
			{name: "fl-us", location: "Miami, US"},
			{name: "fra-de", location: "Frankfurt, DE"},
			{name: "ga-us", location: "Atlanta, US"},
			{name: "hnd-jp", location: "Tokyo, JP"},
			{name: "hon-hi-us", location: "Honolulu, US"},
			{name: "il-us", location: "Chicago, US"},
			{name: "lax-ca-us", location: "Los Angeles, US"},
			{name: "lon-gb", location: "London, UK"},
			{name: "mad-es", location: "Madrid, ES"},
			{name: "mel-au", location: "Melbourne, AU"},
			{name: "mex-mx", location: "Mexico City, MX"},
			{name: "nj-us", location: "New Jersey, US"},
			{name: "par-fr", location: "Paris, FR"},
			{name: "sao-br", location: "Sao Paulo, BR"},
			{name: "sel-kor", location: "Seoul, KR"},
			{name: "sgp", location: "Singapore, SG"},
			{name: "sjo-ca-us", location: "Silicon Valley, US"},
			{name: "sto-se", location: "Stockholm, SE"},
			{name: "syd-au", location: "Sydney, AU"},
			{name: "tor-ca", location: "Toronto, CA"},
			{name: "tx-us", location: "Dallas, US"},
			{name: "wa-us", location: "Seattle, US"},
			{name: "waw-pl", location: "Warsaw, PL"},
		},
	},
}
